#!/usr/bin/env python3
"""Package the sitter; refuse to replace an existing release artifact."""
import argparse
import hashlib
import json
from pathlib import Path
import zipfile

#: Where the payload's source lives, relative to the repository root, and the
#: only definition of it. Ticket 0697 promoted the sitter out of `bench/`, which
#: is for probes and one-off measurements, to a top-level `plugins/`; the guard
#: in `bench/check_sitter_version.py` reads this rather than restating it, so a
#: further move cannot leave one of the two packaging the old directory.
SOURCE = 'plugins/sdt-sitter'

#: Where the sitter's locales live. A language is added by dropping one file
#: here and naming its tag below; nothing enumerates the directory at runtime,
#: because `bootstrap.js` resolves its fallback chain by trying to fetch each
#: candidate (ticket 0692). This tuple is what packs them.
LOCALES = ('en', 'fr', 'es', 'vi')

#: The payload, and the only definition of it. `bench/check_sitter_version.py`
#: reads this rather than keeping a second list: a file added to the XPI and
#: forgotten by the version guard is a payload that can change without a bump,
#: which is the one thing that guard exists to prevent. `update.json` beside
#: these is deliberately absent — it is served over HTTP, never packed.
#:
#: The `.ftl` files are payload for both reasons at once: an XPI without them
#: shows every string as its own message id, and a translation corrected without
#: a version bump is exactly the two-builds-one-number case the guard is for.
DELIVERED = ('manifest.json', 'bootstrap.js', 'scheduler.js',
             *(f'locale/{tag}/sdt-pack-sitter.ftl' for tag in LOCALES))


#: The generated file that carries the locales into the XPI as JavaScript, and
#: why it exists at all. Ticket 0727: a `.ftl` inside an installed XPI cannot be
#: read at runtime. The add-on is installed packed, so `rootURI` is a
#: `jar:file:///….xpi!/` URL, and every read API the plugin can reach refuses
#: it -- `Zotero.File.getContentsFromURLAsync` throws before it even opens the
#: archive (`NS_ERROR_FAILURE [nsIURI.username]`, its HTTP layer cannot parse a
#: `jar:` URI), and `fetch` answers NetworkError. Measured in the author's own
#: Zotero 10.0.1, not inferred.
#:
#: What DOES read that archive is `Services.scriptloader.loadSubScript`, which
#: is how `scheduler.js` has loaded on every startup this plugin has ever had.
#: So the locales travel by the one road known to be open: packed as a script
#: that assigns them, loaded the same way the scheduler is.
#:
#: The `.ftl` files stay the source of truth -- a translator edits those, the
#: tests read those, and this is generated from them at pack time. It is
#: deliberately NOT in `DELIVERED`: that tuple is the payload the version guard
#: hashes out of the repository, and a file that exists only inside the built
#: XPI has nothing there to hash. Its content is a pure function of the `.ftl`
#: files, which ARE hashed, so a locale change still moves the payload digest.
GENERATED = 'locales.js'


def locales_script(source: Path) -> bytes:
    """The `.ftl` sources as one assignment, for `loadSubScript` to evaluate.

    `json.dumps` does the escaping, which is the whole reason this is generated
    rather than hand-maintained: a translation carrying a quote, a backslash or
    a line separator has to survive becoming a JavaScript string literal, and
    hand-escaping four files is a defect waiting for its first apostrophe.
    """
    sources = {tag: (source / f'locale/{tag}/sdt-pack-sitter.ftl').read_text(encoding='utf-8')
               for tag in LOCALES}
    return ('/* Generated by bench/build_sdt_sitter.py from the .ftl files.\n'
            '   Do not edit: edit plugins/sdt-sitter/locale/<tag>/sdt-pack-sitter.ftl.\n'
            '   Exists because a .ftl inside a packed XPI cannot be read at runtime\n'
            '   (ticket 0727); this travels by loadSubScript, which can. */\n'
            f'var SDT_LOCALE_SOURCES = {json.dumps(sources, ensure_ascii=False)};\n'
            ).encode('utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    source = Path(__file__).resolve().parent.parent / SOURCE
    names = DELIVERED
    with zipfile.ZipFile(args.output, 'x', compression=zipfile.ZIP_DEFLATED) as package:
        for name in names:
            entry = zipfile.ZipInfo(name, (2026, 9, 5, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o644 << 16
            package.writestr(entry, (source / name).read_bytes())
        entry = zipfile.ZipInfo(GENERATED, (2026, 9, 5, 0, 0, 0))
        entry.compress_type = zipfile.ZIP_DEFLATED
        entry.external_attr = 0o644 << 16
        package.writestr(entry, locales_script(source))
    print(json.dumps({'path': str(args.output),
                      'sha256': hashlib.sha256(args.output.read_bytes()).hexdigest(),
                      'sourceSHA256': {name: hashlib.sha256((source / name).read_bytes()).hexdigest()
                                       for name in names}}, indent=2))


if __name__ == '__main__':
    main()
